authorization:

    env: laravel-env
    rr: laravel-rr

    ingress:
        enabled: true
        className: "nginx"
        hosts:
            -   host: arch.homework
                paths:
                    -   path: /
                        pathType: Prefix
