version: "3"

rpc:
    listen: tcp://127.0.0.1:6001

server:
    command: "php vendor/bin/roadrunner-worker start"
    env:
        APP_BASE_PATH: "/var/www/html"
        LARAVEL_OCTANE: "1"

        XDEBUG_SESSION: "xdebug"
        PHP_IDE_CONFIG: "serverName=localhost"
    relay: pipes

http:
    address: 0.0.0.0:8000
    middleware: [
        "static",
        "gzip",
    ]
    static:
        dir: "/var/www/html/public"
        forbid: [
            ".php",
            ".htaccess",
        ]
    gzip:
        level: 6
    pool:
        debug: true
        num_workers: 1
        # max_jobs: 1000
        supervisor:
            exec_ttl: 300s

logs:
    mode: production
    level: debug
