apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: authorization
    namespace: fa
spec:
    ingressClassName: nginx
    rules:
        -   host: authorization.local
            http:
                paths:
                    -   path: /
                        pathType: Prefix
                        backend:
                            service:
                                name: authorization-authorization
                                port:
                                    number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: profile
    namespace: fa
    annotations:
        nginx.ingress.kubernetes.io/auth-url: http://authorization-authorization.fa.svc.cluster.local/api/me
        nginx.ingress.kubernetes.io/auth-response-headers: X-API-KEY
spec:
    ingressClassName: nginx
    rules:
        -   host: profile.local
            http:
                paths:
                    -   path: /
                        pathType: Prefix
                        backend:
                            service:
                                name: profile-profile
                                port:
                                    number: 80
