apiVersion: v1
kind: Secret
metadata:
    name: msa-application-laravel-env
    labels:
        app.kubernetes.io/name: msa-application-laravel-env
type: Opaque
stringData:
    .env: |
        APP_NAME="Laravel"
        APP_KEY="base64:mF57EFc73zlZGvQC1E5IeyXHznrNulcNZ4WCZjcEQeo="
        APP_URL="http://arch.homework"

        APP_LOCALE="en"
        APP_FALLBACK_LOCALE="en"
        APP_FAKER_LOCALE="en_US"

        APP_MAINTENANCE_DRIVER="file"

        BCRYPT_ROUNDS="12"

        LOG_CHANNEL="stack"
        LOG_STACK="single"
        LOG_DEPRECATIONS_CHANNEL="null"
        LOG_LEVEL="debug"

        DB_CONNECTION="pgsql"
        DB_HOST="msa-infrastructure-postgres"
        DB_PORT="5432"
        DB_DATABASE="otus"
        DB_USERNAME="otus"
        DB_PASSWORD="otus"

        SESSION_DRIVER="database"
        SESSION_LIFETIME="120"
        SESSION_ENCRYPT="false"
        SESSION_PATH="/"
        SESSION_DOMAIN="null"

        BROADCAST_CONNECTION="log"
        FILESYSTEM_DISK="local"
        QUEUE_CONNECTION="database"

        CACHE_STORE="database"
        CACHE_PREFIX=":otus:"

        MEMCACHED_HOST="127.0.0.1"

        REDIS_CLIENT="phpredis"
        REDIS_HOST="127.0.0.1"
        REDIS_PASSWORD="null"
        REDIS_PORT="6379"

        MAIL_MAILER="log"
        MAIL_SCHEME="null"
        MAIL_HOST="127.0.0.1"
        MAIL_PORT="2525"
        MAIL_USERNAME="null"
        MAIL_PASSWORD="null"
        MAIL_FROM_ADDRESS="hello@example.com"
        MAIL_FROM_NAME="Laravel"

        AWS_ACCESS_KEY_ID=""
        AWS_SECRET_ACCESS_KEY=""
        AWS_DEFAULT_REGION="us-east-1"
        AWS_BUCKET=""
        AWS_USE_PATH_STYLE_ENDPOINT="false"

        VITE_APP_NAME="Laravel"
