apiVersion: v1
kind: Secret
metadata:
    name: {{ include "postgres.fullname" . }}-credentials
    labels:
        {{- include "postgres.labels" . | nindent 8 }}
type: Opaque
data:
    POSTGRES_USER: {{ .Values.env.user | b64enc | quote }}
    POSTGRES_PASSWORD: {{ .Values.env.password | b64enc | quote }}
    POSTGRES_DB: {{ .Values.env.db | b64enc | quote }}
