apiVersion: v1
kind: Service
metadata:
    name: {{ include "postgres.fullname" . }}
    labels:
        {{- include "postgres.labels" . | nindent 8 }}
spec:
    type: {{ .Values.service.type }}
    ports:
        -   port: {{ .Values.service.port }}
            protocol: TCP
            name: postgres
    selector:
        {{- include "postgres.selectorLabels" . | nindent 8 }}
