apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: {{ include "postgres.fullname" . }}
    labels:
        {{- include "postgres.labels" . | nindent 8 }}
spec:
    serviceName: {{ include "postgres.fullname" . }}
    replicas: 1
    selector:
        matchLabels:
            {{- include "postgres.selectorLabels" . | nindent 12 }}
    template:
        metadata:
            labels:
                {{- include "postgres.labels" . | nindent 16 }}
        spec:
            containers:
                -   name: {{ .Chart.Name }}
                    image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
                    imagePullPolicy: {{ .Values.image.pullPolicy }}
                    {{- if .Values.args }}
                    args:
                        {{- range .Values.args }}
                        - {{ . | quote }}
                        {{- end }}
                    {{- end }}
                    ports:
                        -   name: tcp
                            containerPort: {{ .Values.service.port }}
                            protocol: TCP
                    env:
                        -   name: POSTGRES_USER
                            valueFrom:
                                secretKeyRef:
                                    name: {{ include "postgres.fullname" . }}-credentials
                                    key: POSTGRES_USER
                        -   name: POSTGRES_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: {{ include "postgres.fullname" . }}-credentials
                                    key: POSTGRES_PASSWORD
                        -   name: POSTGRES_DB
                            valueFrom:
                                secretKeyRef:
                                    name: {{ include "postgres.fullname" . }}-credentials
                                    key: POSTGRES_DB
                    {{- if .Values.startupProbe.enabled }}
                    startupProbe:
                        exec:
                            command:
                                - sh
                                - -c
                                - exec pg_isready -U {{ .Values.env.user }}
                        initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
                        periodSeconds: {{ .Values.startupProbe.periodSeconds }}
                        timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
                        failureThreshold: {{ .Values.startupProbe.failureThreshold }}
                    {{- end }}
                    {{- if .Values.livenessProbe.enabled }}
                    livenessProbe:
                        exec:
                            command:
                                - sh
                                - -c
                                - exec pg_isready -U {{ .Values.env.user }}
                        initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
                        periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
                        timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
                        failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
                    {{- end }}
                    {{- if .Values.readinessProbe.enabled }}
                    readinessProbe:
                        exec:
                            command:
                                - sh
                                - -c
                                - exec pg_isready -U {{ .Values.env.user }}
                        initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
                        periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
                        timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
                        failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
                    {{- end }}
                    {{- with .Values.resources }}
                    resources:
                        {{- toYaml . | nindent 24 }}
                    {{- end }}
                    volumeMounts:
                        -   name: data
                            mountPath: /var/lib/postgresql/data
    volumeClaimTemplates:
        -   metadata:
                name: data
            spec:
                accessModes:
                    - ReadWriteOnce
                resources:
                    requests:
                        storage: {{ .Values.persistence.size }}
                {{- if .Values.persistence.storageClass }}
                storageClassName: {{ .Values.persistence.storageClass }}
                {{- end }}
