{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ include "msa.fullname" . }}
    labels:
        {{- include "msa.labels" . | nindent 8 }}
spec:
    {{- with .Values.ingress.className }}
    ingressClassName: {{ . }}
    {{- end }}
    rules:
    {{- range .Values.ingress.hosts }}
        -   host: {{ .host | quote }}
            http:
                paths:
                    {{- range .paths }}
                    -   path: {{ .path }}
                    {{- with .pathType }}
                        pathType: {{ . }}
                    {{- end }}
                        backend:
                            service:
                                name: {{ include "msa.fullname" $ }}
                                port:
                                    number: {{ $.Values.service.port }}
                    {{- end }}
    {{- end }}
{{- end }}
