apiVersion: v1
kind: Service
metadata:
    name: {{ include "msa.fullname" . }}
    labels:
        {{- include "msa.labels" . | nindent 8 }}
spec:
    type: {{ .Values.service.type }}
    ports:
        -   port: {{ .Values.service.port }}
            targetPort: {{ .Values.service.targetPort }}
            protocol: TCP
            name: http
    selector:
        {{- include "msa.selectorLabels" . | nindent 8 }}
